# Настройка подключения к эмулятору
appium.server.url=http://127.0.0.1:4723/
device.name=Android Emulator
platform.name=Android
app.package=com.joom
app.activity=com.joom.ui.main.MainActivity
automation.name=UiAutomator2
new.command.timeout=120

# Значения тестовых данных
USER_FIRST_NAME=Alex
USER_LAST_NAME=Alexion
# email в конфиге - просто fallback, в коде он переопределяется на динамический
USER_EMAIL=email@gmail.com
USER_PASSWORD=TesT!1234
USER_PASSWORD_CONFIRMATION=TesT!1234